### ISSUE TITLE
Consider multivalue field reordering

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ckeditor5#90] opened 2023-11-08 15:25 UTC
Definitely an edge case, but eventually feasible...

Currently, with multivalue fields (field cardinality > 1), the editor content gets saved properly, when new fields get added. :+1: 

But reordering these multivalue field (via drag/drop) also detaches the editor. We might want to re-attach it (Backdrop.editors.ckeditor5.attach()), if the "trigger" is "move".
Unfortunately I don't really understand the code in Backdrop.editors.ckeditor5.detach.

Not urgent, I guess. :wink:

**Comment by quicksketch** [comment] 2023-11-10 22:00
Thanks @indigoxela, I confirmed this problem but it seems to be in core. The same problem exists for CKEditor 4 and probably every other editor, since what's happening here is that the editors are getting detached on drag, but not reattached. I'm moving this to core and we can continue there.

**Comment by quicksketch** [comment] 2023-11-10 22:10
Apparently we can't move issues from contrib -> core, so I made a new one at https://github.com/backdrop/backdrop-issues/issues/6287.

**Closed as completed by quicksketch** 2023-11-10 22:10 UTC
